jdrouet/catapulte

- Dockerfile
- readme.md
> doc: add how to use it section

- .circleci/config.yml
- script/html-coverage.sh
- script/local-coverage.sh
- script/push-coverage.sh
- script/run-coverage.sh
- src/controller/status.rs
- src/controller/template_send_json.rs
- src/controller/template_send_multipart.rs
- src/error.rs
- src/main.rs
- src/service/smtp.rs
- src/service/template/provider/jolimail.rs
- src/service/template/provider/local.rs
- src/service/template/provider/mod.rs
- src/service/template/template.rs
- src/test_util.rs
> coverage: remove grcov

- app.json
- readme.md
> doc: add button to deploy to heroku

- multiarch.Dockerfile
> build: create dockerfile working in multiarch for arm32v7

- src/controller/template_send_json.rs
- src/controller/template_send_multipart.rs
- src/service/smtp.rs
- src/service/template/provider/jolimail.rs
- src/service/template/provider/local.rs
- src/service/template/provider/mod.rs
- src/service/template/template.rs
> clean: apply clippy changes

- Cargo.toml
> deps: upgrade mrml

- Cargo.toml
> build(deps): update actix-*

- src/main.rs
> fix: use current version as X-Version header

- openapi.yml
- readme.md
> docs: create openapi file

- app.json
- heroku.Dockerfile
- heroku.yml
> feat(heroku): use container stack and define required files

- .travis.yml
- Makefile
- src/service/template/mod.rs
> test(clippy): add clippy step on ci

- src/controller/template_send_json.rs
- src/controller/template_send_multipart.rs
- src/service/template/template.rs
> feat: can set multiple emails in to, cc and bcc

- .gitlab-ci.yml
> ci: move to gitlab ci

- Cargo.toml
> build(deps): Bump mrml from 0.4.0 to 0.5.0

- Cargo.lock
- src/main.rs
- src/service/smtp.rs
- src/service/template/provider/jolimail.rs
- src/service/template/provider/mod.rs
> fix(test): replace localhost by 127.0.0.1 for local tests

- Cargo.lock
- Cargo.toml
- src/controller/status.rs
- src/controller/template_send_json.rs
- src/controller/template_send_multipart.rs
- src/error.rs
- src/service/multipart.rs
- src/service/smtp.rs
- src/service/template/template.rs
> chore(deps): update dependencies

- .gitlab-ci.yml
- script/integration.sh
> Run integration testing

- Cargo.lock
- Cargo.toml
- Dockerfile
- Makefile
- multiarch.Dockerfile
- src/service/template/provider/jolimail.rs
> feat(rustls): replace native-tls by rustls

- src/controller/template_send_multipart.rs
> fix: please clippy

- .dockerignore
- Dockerfile
- alpine.Dockerfile
> fix(docker): remove Cargo.lock from dockerignore

- src/service/template/template.rs
> fix: reorder struct attributes

- .github/semantic.yml
> chore(ci): add commitizen build step

- Cargo.lock
- Cargo.toml
- src/controller/template_send_multipart.rs
- src/service/multipart.rs
- src/service/template/template.rs
> chore(deps): bump lettre to version 0.10.0-rc.1

- Cargo.lock
- Cargo.toml
- openapi.yml
- src/controller/status.rs
- src/main.rs
> enhancement(server): status endpoint now returns uptime

- src/controller/templates/json.rs
- src/middleware/authentication.rs
- swagger/openapi.json
> fix(server): add Bearer in the authentication header

- src/error.rs
- src/service/multipart.rs
- src/service/template/error.rs
- src/service/template/template.rs
> fix(ci): apply clippy's proposals

- Cargo.lock
- Cargo.toml
- src/error.rs
- src/main.rs
- src/middleware/authentication.rs
> chore(server): update actix-web versions

- .gitlab-ci.yml
> chore(ci): only build canary images for amd64

- Cargo.lock
- Cargo.toml
- src/controller/swagger.rs
- src/controller/templates/multipart.rs
- src/middleware/authentication.rs
- src/service/jsonwebtoken.rs
- src/service/multipart.rs
> build(deps): Bump actix packages

- Cargo.lock
- Cargo.toml
> build(deps): Bump lettre to 0.10.0-rc4

- Cargo.lock
- Cargo.toml
- src/config.rs
> build(deps): Bump clap from 3.0.0-beta.5 to 3.0.0

- .gitlab-ci.yml
> fix(ci): avoid hanging on apk add

- Cargo.lock
- Cargo.toml
- src/controller/templates/json.rs
- src/controller/templates/multipart.rs
- src/main.rs
> build(deps): Bump actix-web, actix-http and actix-multipart

- readme.md
> fix: invalid docker image tag

- src/controller/templates/json.rs
> fix: apply clippy suggestions

- Cargo.lock
- Cargo.toml
> build(deps): Bump clap to 4.0.10

- Cargo.lock
- Cargo.toml
> build(deps): bump serial_test to 0.9

- alpine.Dockerfile
> build(deps): bump alpine image version

- Dockerfile
- multiarch.Dockerfile
> build(docker): bump docker images to bulleye

- Cargo.toml
> build(deps): upgrade actix deps

- Dockerfile
- alpine.Dockerfile
- src/action/mod.rs
- src/action/openapi.rs
- src/action/serve.rs
- src/controller/mod.rs
- src/main.rs
> feat(openapi): create a command to print the openapi json schema

- src/service/provider/local.rs
- src/service/provider/mod.rs
- src/service/provider/prelude.rs
- template/user-login/metadata.json
> feat(provider): update local provider

- Cargo.lock
- Cargo.toml
- src/controller/templates/json.rs
- src/controller/templates/multipart.rs
> build(deps): Bump utoipa and utoipa-swagger-ui to 3.0

- Dockerfile
- alpine.Dockerfile
- src/main.rs
> feat: allow to disable color in logs
